# Generated by Django 4.2.3 on 2023-09-21 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0009_ewaybill_ewaybillitem_transportation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurring_invoice',
            name='cname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
